### PR TITLE
Fix class2tree bug

### LINKED ISSUE #689: class2tree generates wrong classification table for organisms with unique rank lower than non-unique ranks
An example goes below
```r
library(taxize)
library(taxizedb)
organisms = c("Haloarcula amylolytica JCM 13557",
              "Haloarcula argentinensis DSM 12282",
              "Haloarcula californiae ATCC 33799",
              "Halarchaeum acidiphilum MH1-52-1")
taxon_IDs = name2taxid(organisms)
taxon_IDs
## [1] "1227452" "1230451" "662475"  "1261545"

classes = taxizedb::classification(taxon_IDs, db = "ncbi")
classes
## $`1227452`
##                               name         rank      id
## 1               cellular organisms      no rank  131567
## 2                          Archaea superkingdom    2157
## 3                    Euryarchaeota       phylum   28890
## 4                     Halobacteria        class  183963
## 5                  Halobacteriales        order    2235
## 6                   Haloarculaceae       family 1963268
## 7                       Haloarcula        genus    2237
## 8           Haloarcula amylolytica      species  396317
## 9 Haloarcula amylolytica JCM 13557      no rank 1227452
## 
## $`1230451`
##                                 name         rank      id
## 1                 cellular organisms      no rank  131567
## 2                            Archaea superkingdom    2157
## 3                      Euryarchaeota       phylum   28890
## 4                       Halobacteria        class  183963
## 5                    Halobacteriales        order    2235
## 6                     Haloarculaceae       family 1963268
## 7                         Haloarcula        genus    2237
## 8           Haloarcula argentinensis      species   43776
## 9 Haloarcula argentinensis DSM 12282      no rank 1230451
## 
## $`662475`
##                                name         rank      id
## 1                cellular organisms      no rank  131567
## 2                           Archaea superkingdom    2157
## 3                     Euryarchaeota       phylum   28890
## 4                      Halobacteria        class  183963
## 5                   Halobacteriales        order    2235
## 6                    Haloarculaceae       family 1963268
## 7                        Haloarcula        genus    2237
## 8            Haloarcula californiae      species  244363
## 9 Haloarcula californiae ATCC 33799      no rank  662475
## 
## $`1261545`
##                               name         rank      id
## 1               cellular organisms      no rank  131567
## 2                          Archaea superkingdom    2157
## 3                    Euryarchaeota       phylum   28890
## 4                     Halobacteria        class  183963
## 5                  Halobacteriales        order    2235
## 6                 Halobacteriaceae       family    2236
## 7                      Halarchaeum        genus  744724
## 8          Halarchaeum acidiphilum      species  489138
## 9 Halarchaeum acidiphilum MH1-52-1      no rank 1261545
## 
## attr(,"class")
## [1] "classification"
## attr(,"db")
## [1] "ncbi"

tr = class2tree(classes)
tr$classification
##                                                               species
## Haloarcula amylolytica JCM 13557     Haloarcula amylolytica JCM 13557
## Haloarcula argentinensis DSM 12282 Haloarcula argentinensis DSM 12282
## Haloarcula californiae ATCC 33799   Haloarcula californiae ATCC 33799
## Halarchaeum acidiphilum MH1-52-1     Halarchaeum acidiphilum MH1-52-1
##                                                  species.1              species.2
## Haloarcula amylolytica JCM 13557                      <NA>                   <NA>
## Haloarcula argentinensis DSM 12282                    <NA>                   <NA>
## Haloarcula californiae ATCC 33799                     <NA> Haloarcula californiae
## Halarchaeum acidiphilum MH1-52-1   Halarchaeum acidiphilum                   <NA>
##                                    species.3                species.4 species.5
## Haloarcula amylolytica JCM 13557        <NA>                     <NA>      <NA>
## Haloarcula argentinensis DSM 12282      <NA> Haloarcula argentinensis      <NA>
## Haloarcula californiae ATCC 33799       <NA>                     <NA>      <NA>
## Halarchaeum acidiphilum MH1-52-1        <NA>                     <NA>      <NA>
##                                    species.6 species.7              species.8
## Haloarcula amylolytica JCM 13557        <NA>      <NA> Haloarcula amylolytica
## Haloarcula argentinensis DSM 12282      <NA>      <NA>                   <NA>
## Haloarcula californiae ATCC 33799       <NA>      <NA>                   <NA>
## Halarchaeum acidiphilum MH1-52-1        <NA>      <NA>                   <NA>
##                                    species.9 species.10 species.11 species.12
## Haloarcula amylolytica JCM 13557        <NA>       <NA>       <NA>       <NA>
## Haloarcula argentinensis DSM 12282      <NA>       <NA>       <NA>       <NA>
## Haloarcula californiae ATCC 33799       <NA>       <NA>       <NA>       <NA>
## Halarchaeum acidiphilum MH1-52-1        <NA>       <NA>       <NA>       <NA>
##                                    species.13 species.14 species.15       genus
## Haloarcula amylolytica JCM 13557         <NA>       <NA>       <NA>  Haloarcula
## Haloarcula argentinensis DSM 12282       <NA>       <NA>       <NA>  Haloarcula
## Haloarcula californiae ATCC 33799        <NA>       <NA>       <NA>  Haloarcula
## Halarchaeum acidiphilum MH1-52-1         <NA>       <NA>       <NA> Halarchaeum
##                                              family           order        class
## Haloarcula amylolytica JCM 13557     Haloarculaceae Halobacteriales Halobacteria
## Haloarcula argentinensis DSM 12282   Haloarculaceae Halobacteriales Halobacteria
## Haloarcula californiae ATCC 33799    Haloarculaceae Halobacteriales Halobacteria
## Halarchaeum acidiphilum MH1-52-1   Halobacteriaceae Halobacteriales Halobacteria
##                                           phylum superkingdom      norank_131567
## Haloarcula amylolytica JCM 13557   Euryarchaeota      Archaea cellular organisms
## Haloarcula argentinensis DSM 12282 Euryarchaeota      Archaea cellular organisms
## Haloarcula californiae ATCC 33799  Euryarchaeota      Archaea cellular organisms
## Halarchaeum acidiphilum MH1-52-1   Euryarchaeota      Archaea cellular organisms
```

### PR DESCRIPTION
**Pull request by gpli**
organisms with unique rank lower than non-unique ranks will give extra wrong rows in 'taxonomy_table_creator' function

## Description

Check existence of the lowest non-unique rank (i.e. 'species') before rbind

## Related Issue

fix #689

## Example

```
library(taxize)
library(taxizedb)
organisms = c("Haloarcula amylolytica JCM 13557",
              "Haloarcula argentinensis DSM 12282",
              "Haloarcula californiae ATCC 33799",
              "Halarchaeum acidiphilum MH1-52-1")
taxon_IDs = name2taxid(organisms)
taxon_IDs
## [1] "1227452" "1230451" "662475"  "1261545"

classes = taxizedb::classification(taxon_IDs, db = "ncbi")
tr = class2tree(classes)
tr$classification
##                                                     species       genus
## Haloarcula amylolytica JCM 13557     Haloarcula amylolytica  Haloarcula
## Haloarcula argentinensis DSM 12282 Haloarcula argentinensis  Haloarcula
## Haloarcula californiae ATCC 33799    Haloarcula californiae  Haloarcula
## Halarchaeum acidiphilum MH1-52-1    Halarchaeum acidiphilum Halarchaeum
##                                              family           order        class
## Haloarcula amylolytica JCM 13557     Haloarculaceae Halobacteriales Halobacteria
## Haloarcula argentinensis DSM 12282   Haloarculaceae Halobacteriales Halobacteria
## Haloarcula californiae ATCC 33799    Haloarculaceae Halobacteriales Halobacteria
## Halarchaeum acidiphilum MH1-52-1   Halobacteriaceae Halobacteriales Halobacteria
##                                           phylum superkingdom      norank_131567
## Haloarcula amylolytica JCM 13557   Euryarchaeota      Archaea cellular organisms
## Haloarcula argentinensis DSM 12282 Euryarchaeota      Archaea cellular organisms
## Haloarcula californiae ATCC 33799  Euryarchaeota      Archaea cellular organisms
## Halarchaeum acidiphilum MH1-52-1   Euryarchaeota      Archaea cellular organisms
```

### CODE REVIEW

**Comment by sckott** [comment]
thanks for this PR @gpli 

having a look at it now

**Comment by sckott** [comment]
@gpli can you add a test to https://github.com/ropensci/taxize/blob/master/tests/testthat/test-class2tree.R to address the fixed problem

**Comment by gpli** [comment]
@sckott the test has been added.

**Comment by sckott** [comment]
thanks very much @gpli !

**Pull request merged**
