### PR TITLE
 docs: update vignette, base R only,  typos, fix #544

### LINKED ISSUE #544: more vignettes

### PR DESCRIPTION
**Pull request by fozy81**
## Description

New vignette showcasing resolve function using Carl Linnaeus' binomial names from 1752
Related Issue

## Related Issue

fix #544

## Example

More vignettes and use cases. Includes new data file of Carl Linnaeus species (dataframe of 5490 species names).

### CODE REVIEW

**Comment by fozy81** [comment]
Hope this is still useful :pray: . Sorry it's taken so long to address your comments in the last PR. Let me know if this is going in the right direction. I've signed up to the red data list API so may include that in future update.

**Comment by sckott** [comment]
thanks @fozy81 

Instead of putting the .Rmd unrendered into `vignettes/` put the rendered `.md` from `inst/vign` into `vignettes/` - the vignette does take a long time to build, which I want to avoid, but we can put the rendered version in there

**Comment by sckott** [comment]
@fozy81 are you still planning to finish this?

**Comment by fozy81** [comment]
Yep, sorry. Will complete soon.

**Comment by fozy81** [comment]
@sckott I've removed the .Rmd unrendered from vignettes/ and put the rendered .md from inst/vign into vignettes/. Package/vignettes build quickly now.

**Comment by sckott** [comment]
looks good @fozy81 thanks very much

**Pull request merged**
