### PR TITLE
Add options for IUCN summary (2nd try)

### PR DESCRIPTION
**Pull request by pmarchand1**
- Added a distr_detail optional parameter to iucn_summary; if TRUE, the distr element is a list of up to two elements (native and introduced range) rather than just a vector of countries.

- Added an iucn_summary_from_id function, and to reduce duplication of code, made both iucn_summary and iucn_summary_from_id call a non-exported function get_iucn_summary.

Note that I was only able to test iucn_summary_from_id since my IUCN API key request is still waiting approval. Hopefully this is not a problem since the rredlist portion of iucn_summary is not affected by these edits.

### CODE REVIEW

**Comment by sckott** [comment]
don't know if you know, but you can add commits to a PR, just commit on the `iucn_add_features` branch, you don't have to open a new PR

**Comment by sckott** [comment]
@pmarchand1 Note that `iucn_getname()` uses `iucn_summary()` https://github.com/ropensci/taxize/blob/master/R/iucn_getname.R - make sure `iucn_getname()` doesn't break b/c of the changes -> see test results above, they point out some test failures

**Comment by pmarchand1** [comment]
@sckott It seems there' s a problem with the API key based on the log.

>   test_check("taxize")
> 
>   1. Failure (at test-iucn_getname.R#6): iucn_getname returns the correct value --
>   temp not equal to "Parus caeruleus"
>   Lengths (0, 1) differ
>   1 string mismatches:
>   y[1]: "Parus caeruleus"
> 
>   2. Failure (at test-iucn_getname.R#14): iucn_getname gets the right dimensions -
>   length(temp) not equal to 1
>   0 - 1 == -1
>   Error: need an API key for Red List data
>   Execution halted

**Comment by sckott** [comment]
@pmarchand1 Ah, sorry. Right, need API key. I have that key set on Travis-CI, but they aren't avail. for pull requests, I'll pull down and test locally...and get back to you

**Comment by sckott** [comment]
Looks good. Can you please add tests for the new functionality of the function?

**Comment by sckott** [comment]
* If okay with you, can we change the fxn name to maybe `iucn_summary_id()`  
* add some examples for your new fxn

**Comment by pmarchand1** [comment]
Made these edits in the last commit. I was received my IUCN token, so was able to test locally.

**Comment by sckott** [comment]
awesome thanks @pmarchand1 a few more things:

* can you update your `roxygen2` version so that there are differences in man files due to that, should have `v5.0.1`
* run `document()` or `roxygenize()` again - your new function wasn't in `NAMESPACE`
* add your name as author to the `iucn_summary` fxn

**Comment by pmarchand1** [comment]
Oh, I had forgot to add `NAMESPACE` to the commit. Fixed now! Thank you.

**Comment by sckott** [comment]
thanks! LGTM

**Pull request merged**
